export const ARTICLE_SHELL_MAX_WIDTH = 1440
export const ARTICLE_TOC_WIDTH = 256
export const ARTICLE_TOC_GAP = 36
export const ARTICLE_TREE_WIDTH = 256
export const ARTICLE_TREE_GAP = 36
export const ARTICLE_DESKTOP_TOC_BREAKPOINT = 1024
export const ARTICLE_RAIL_MAX_EN_REM = 49
export const ARTICLE_RAIL_MAX_ZH_REM = 56
export const ARTICLE_SURFACE_CHROME_DEDUCTION =
  ARTICLE_TOC_WIDTH + ARTICLE_TOC_GAP + ARTICLE_TREE_GAP + ARTICLE_TREE_WIDTH
