import { existsSync } from 'node:fs'
import { readFile, readdir, rename, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import { formatBytes } from './lib/file-utils.mjs'

const imageDir = path.join('public', 'static', 'images')
const manifestPath = path.join('lib', 'generated', 'image-manifest.ts')
const supportedExtensions = new Set(['.jpg', '.jpeg', '.png'])
const checkOnly = process.argv.includes('--check')

const IMAGE_OPTIMIZATION_PRESETS = {
  maxPhotoWidth: 2000,
  maxRasterWidth: 1600,
  jpegQuality: 82,
  pngCompressionLevel: 9,
  webpQuality: 78,
}

// Must match RESPONSIVE_WIDTHS in lib/images.ts so the runtime srcset and the
// generated variant files stay in sync.
const RESPONSIVE_WIDTHS = [400, 640, 768, 1024, 1280]

/**
 * @param {string} filePath - source image path
 * @param {number} width - responsive width variant
 * @returns {string}
 */
function variantPath(filePath, width) {
  const ext = path.extname(filePath)
  return `${filePath.slice(0, filePath.length - ext.length)}.${width}.webp`
}

/**
 * @param {string} filePath - source image path
 * @returns {string}
 */
function imageSrc(filePath) {
  const rel = path.relative(process.cwd(), filePath).split(path.sep).join('/')

  return rel.startsWith('public/') ? `/${rel.slice('public/'.length)}` : `/${rel}`
}

/**
 * @param {number} sourceWidth - original image width (0 when unknown)
 * @returns {number[]}
 */
function expectedVariantWidths(sourceWidth) {
  if (!sourceWidth) return [...RESPONSIVE_WIDTHS]
  return RESPONSIVE_WIDTHS.filter((width) => width <= sourceWidth)
}

/**
 * @param {{ src: string, widths: number[], width: number, height: number }[]} entries
 * @returns {string}
 */
function serializeManifest(entries) {
  const sorted = [...entries].sort((a, b) => a.src.localeCompare(b.src))
  const lines = sorted.map(
    (entry) =>
      `  ${JSON.stringify(entry.src)}: { widths: [${entry.widths.join(', ')}], width: ${entry.width}, height: ${entry.height} },`
  )

  return (
    '// Generated by scripts/optimize-images.mjs. Do not edit by hand.\n' +
    'export type ImageEntry = { widths: number[]; width: number; height: number }\n' +
    'export const imageManifest: Record<string, ImageEntry> = {\n' +
    `${lines.join('\n')}\n` +
    '}\n'
  )
}

/**
 * @param {string} filePath - source image path
 * @returns {Promise<void>}
 */
async function optimizeOriginal(filePath) {
  const ext = path.extname(filePath).toLowerCase()
  const before = (await stat(filePath)).size
  const tempPath = `${filePath}.tmp`
  let pipeline = sharp(filePath).rotate()

  if (ext === '.jpg' || ext === '.jpeg') {
    pipeline = pipeline
      .resize({ width: IMAGE_OPTIMIZATION_PRESETS.maxPhotoWidth, withoutEnlargement: true })
      .jpeg({ quality: IMAGE_OPTIMIZATION_PRESETS.jpegQuality, mozjpeg: true })
  } else if (ext === '.png') {
    pipeline = pipeline
      .resize({ width: IMAGE_OPTIMIZATION_PRESETS.maxRasterWidth, withoutEnlargement: true })
      .png({
        compressionLevel: IMAGE_OPTIMIZATION_PRESETS.pngCompressionLevel,
        adaptiveFiltering: true,
      })
  }

  await pipeline.toFile(tempPath)
  const after = (await stat(tempPath)).size

  if (after >= before) {
    await rm(tempPath, { force: true })
    console.log(`kept      ${formatBytes(before).padStart(9)}  ${filePath}`)
    return
  }

  await rename(tempPath, filePath)
  console.log(
    `optimized ${formatBytes(before).padStart(9)} -> ${formatBytes(after).padStart(9)}  ${filePath}`
  )
}

/**
 * @param {string} filePath - source image path
 * @returns {Promise<void>}
 */
async function generateVariants(filePath) {
  const ext = path.extname(filePath).toLowerCase()

  if (!supportedExtensions.has(ext)) {
    return
  }

  const meta = await sharp(filePath).metadata()
  const widths = expectedVariantWidths(meta.width || 0)

  for (const width of widths) {
    const target = variantPath(filePath, width)

    await sharp(filePath)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: IMAGE_OPTIMIZATION_PRESETS.webpQuality })
      .toFile(target)
  }
}

/**
 * @param {string} filePath - source image path
 * @returns {Promise<{ src: string, widths: number[], width: number, height: number }>}
 */
async function processImage(filePath) {
  const meta = await sharp(filePath).metadata()
  const sourceWidth = meta.width || 0
  const widths = expectedVariantWidths(sourceWidth)

  if (checkOnly) {
    const missing = []

    for (const width of widths) {
      if (!existsSync(variantPath(filePath, width))) {
        missing.push(variantPath(filePath, width))
      }
    }

    if (missing.length > 0) {
      throw new Error(`missing responsive variants:\n  ${missing.join('\n  ')}`)
    }
  } else {
    await optimizeOriginal(filePath)
    await generateVariants(filePath)
  }

  return {
    src: imageSrc(filePath),
    widths,
    width: sourceWidth,
    height: meta.height || 0,
  }
}

const failures = []
const manifestEntries = []

for (const entry of await readdir(imageDir, { withFileTypes: true })) {
  if (!entry.isFile()) {
    continue
  }

  const filePath = path.join(imageDir, entry.name)

  if (!supportedExtensions.has(path.extname(entry.name).toLowerCase())) {
    continue
  }

  try {
    manifestEntries.push(await processImage(filePath))
  } catch (error) {
    failures.push({ filePath, message: error instanceof Error ? error.message : String(error) })
    console.error(`failed    ${filePath}: ${failures[failures.length - 1].message}`)
  }
}

const nextManifest = serializeManifest(manifestEntries)

if (checkOnly) {
  const currentManifest = existsSync(manifestPath) ? await readFile(manifestPath, 'utf8') : ''

  if (currentManifest !== nextManifest) {
    failures.push({
      filePath: manifestPath,
      message: 'image manifest is out of date. Run `yarn images:optimize`.',
    })
  } else {
    console.log('Responsive image variants and manifest are up to date')
  }
} else {
  await writeFile(manifestPath, nextManifest)
  console.log(`Wrote image manifest with ${manifestEntries.length} entries`)
}

if (failures.length > 0) {
  console.error(`\n${failures.length} image(s) failed:`)
  for (const failure of failures) {
    console.error(`  ${failure.filePath}: ${failure.message}`)
  }
  process.exit(1)
}
